### ISSUE TITLE
how to config

### ISSUE THREAD

**Issue by mads5434** [MarkehMe/FactionsAlias#4]
yea, im really bad at it, but i would love if someone could help me do so they dont have to do /f invite a [name] to just /f invite [name] :P 
Only asking for help cuz im really bad at this kind of stuff :(

**Comment by markhughes** [comment]
```
aliases:
  invite:
    aliases: 
    - invite
    execute: f inv a
    requires:
      factionsEnabledInWorld: true
      executerIsPlayer: true
      executerIsInFaction: true
    permission: factions.invite
    permissionDeniedMessage: '§4You dont have permission to do this!'
    description: 'Invite a player to the faction'
```
